name: Generate Icon CSS with Gulp

on:
  push:
    paths:
      - 'src/assets/images/*.svg'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm i

      - name: Run Gulp iconfont task
        run: npx gulp iconfont
