name: Download Updated CSS

on:
  workflow_run:
    workflows: ["Generate Icon CSS with Gulp"]
    types:
      - completed

jobs:
  download:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: updated-css
          path: downloaded_files